### ISSUE TITLE
Update constants.h

### ISSUE THREAD

**Issue by lalit-03** [nilis24/physics.h#15] opened 2022-10-01 14:25 UTC
Add the following constants to constants.h :
1) Speed of Light
2) Planck Constant
3) Boltzmann Constant
4) Coulomb Constant
5) Stefan-Boltzmann Constant
6) Faraday Constant
7) Avogadro's Number
8) Permittivity of vacuum(ε0)

**Comment by WaniAthar** [comment] 2022-10-01 14:33
@lalit-03 i would like to work on it

**Comment by Antibodyy** [comment] 2022-10-01 14:45
I have all these topics in my current coursework. I would like to work on this, plus it would help me in revising a bit.

**Comment by nilis24** [comment] 2022-10-01 14:47
@lalit-03 assigned to you. @WaniAthar @Antibodyy please read CONTRIBUTING.md you can be assigned to a issue if th issue is created by you, but If the issue is created by the owner (me) or an admin, then you can ask to be assigned

**Comment by Antibodyy** [comment] 2022-10-01 14:51
Ok. Gotchu

**Comment by nilis24** [comment] 2022-10-01 15:03
well wait. I didn't realize that lalit-03 didn't ask me to assign the problem to him/her. Sorry, I'm a novice maintainer, hope you understand. So, @lalit-03 do you want to work on this issue? If not I will assign it to you @Antibodyy

**Comment by lalit-03** [comment] 2022-10-01 15:49
I'll work on it @nilis24.

**Comment by Fonta22** [comment] 2022-10-01 15:58
Perfect, assigned it to you. @lalit-03

**Comment by YashAdake** [comment] 2022-10-01 18:24
Sorry for mistakenly I made a few changes to this. As a newbie, I didn't know the Issues section and all so I just made them.

**Closed** 2022-10-02 12:12 UTC
Labels: hacktoberfest
